import { readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

// Generates design/tokens.generated.css from design/TOKENS.json.
//
// Scope is deliberately narrow: only the 6 semantic color keys that DESIGN.md §2.2's
// "Existing theme mapping" table actually tracks (surface/canvas/human/agent/rpg/danger),
// plus the theme-independent spacing/radius/motion scale. `onSurface` and `line` are NOT
// generated here — Current (root styles.css) and Next (interaction-lab/styles.css) use
// meaningfully different ink/line values by design (confirmed by direct comparison), so
// aliasing them would be a real value change dressed up as a rename.
//
// Each theme/mode combo is emitted under BOTH attribute schemes so the same custom
// properties resolve on both surfaces without any runtime/JS changes:
//   - Next:    :root[data-qf-theme="X"][data-qf-resolved-mode="Y"]
//   - Current: body[data-theme="x"]              (Y = light)
//              html[data-color-mode="dark"] body[data-theme="x"]  (Y = dark)

const root = resolve(process.cwd());
const tokensPath = join(root, "design/TOKENS.json");
const outputPath = join(root, "design/tokens.generated.css");

interface ThemeColors {
  surface: string; canvas: string; human: string; agent: string; rpg: string; danger: string;
  onSurface: string; line: string;
}
interface Tokens {
  themes: Record<"arcane" | "soft-ops" | "retro", { light: ThemeColors; dark: ThemeColors }>;
  spacing: Record<string, string>;
  radius: Record<string, string>;
  motion: { hover: string; panel: string; bottomSheet: string; easing: string; retroEasing: string };
}

// Current surface's `body[data-theme]` attribute value differs from the theme id for soft-ops
// only ("soft", not "soft-ops") — see DESIGN.md §2.2 2026-08-22 note on the id mismatch.
const currentAttr: Record<string, string> = { arcane: "arcane", "soft-ops": "soft", retro: "retro" };

// Known, deliberate exceptions where Current's shipped pixel value differs from the Next/
// TOKENS.json value by design (or by a pre-existing 1-digit drift out of this pass's scope).
// These keys are skipped for the Current-surface selector only, so root styles.css keeps its
// current literal value untouched — the alias layer must not silently change any pixel.
const currentExceptions = new Set(["arcane|light|surface"]);

function generate(tokens: Tokens): string {
  const lines: string[] = [
    "/* GENERATED by tools/generate-tokens.mts from design/TOKENS.json. Do not edit by hand. */",
    "/* Run `npm run tokens:generate` after changing TOKENS.json, or `npm run tokens:check` to verify no drift. */",
    "",
    ":root {",
    `  --qf-space-xs: ${tokens.spacing.xs};`,
    `  --qf-space-sm: ${tokens.spacing.sm};`,
    `  --qf-space-md: ${tokens.spacing.md};`,
    `  --qf-space-lg: ${tokens.spacing.lg};`,
    `  --qf-space-xl: ${tokens.spacing.xl};`,
    `  --qf-gutter: ${tokens.spacing.gutter};`,
    `  --qf-radius-none: ${tokens.radius.none};`,
    `  --qf-radius-sm: ${tokens.radius.sm};`,
    `  --qf-radius-md: ${tokens.radius.md};`,
    `  --qf-radius-full: ${tokens.radius.full};`,
    `  --qf-motion-hover: ${tokens.motion.hover};`,
    `  --qf-motion-panel: ${tokens.motion.panel};`,
    `  --qf-motion-sheet: ${tokens.motion.bottomSheet};`,
    `  --qf-ease: ${tokens.motion.easing};`,
    `  --qf-ease-retro: ${tokens.motion.retroEasing};`,
    "}",
    "",
  ];

  for (const theme of ["arcane", "soft-ops", "retro"] as const) {
    for (const mode of ["light", "dark"] as const) {
      const colors = tokens.themes[theme][mode];
      const nextSelector = `:root[data-qf-theme="${theme}"][data-qf-resolved-mode="${mode}"]`;
      const currentSelector = mode === "light"
        ? `body[data-theme="${currentAttr[theme]}"]`
        : `html[data-color-mode="dark"] body[data-theme="${currentAttr[theme]}"]`;
      const skipCurrent = new Set<string>();
      for (const key of ["surface", "canvas", "human", "agent", "rpg", "danger"] as const) {
        if (currentExceptions.has(`${theme}|${mode}|${key}`)) skipCurrent.add(key);
      }
      // Next always gets the full set. Current gets the full set minus any exceptions —
      // when there IS an exception, Current is declared as its own separate block that
      // simply omits that one property, leaving root styles.css's own literal declaration
      // (which comes later in cascade order within that file) as the effective value.
      lines.push(`${nextSelector}${skipCurrent.size ? "" : ",\n" + currentSelector} {`);
      lines.push(`  --qf-surface: ${colors.surface};`);
      lines.push(`  --qf-canvas: ${colors.canvas};`);
      lines.push(`  --qf-human: ${colors.human};`);
      lines.push(`  --qf-agent: ${colors.agent};`);
      lines.push(`  --qf-rpg: ${colors.rpg};`);
      lines.push(`  --qf-danger: ${colors.danger};`);
      lines.push("}");
      if (skipCurrent.size) {
        const props: Record<string, string> = { surface: "--qf-surface", canvas: "--qf-canvas", human: "--qf-human", agent: "--qf-agent", rpg: "--qf-rpg", danger: "--qf-danger" };
        const remaining = (["surface", "canvas", "human", "agent", "rpg", "danger"] as const).filter((key) => !skipCurrent.has(key));
        if (remaining.length) {
          lines.push(`${currentSelector} {`);
          for (const key of remaining) lines.push(`  ${props[key]}: ${colors[key]};`);
          lines.push(`  /* ${[...skipCurrent].join(", ")} intentionally omitted here — see currentExceptions in tools/generate-tokens.mts */`);
          lines.push("}");
        }
      }
      lines.push("");
    }
  }
  return lines.join("\n");
}

async function main(): Promise<void> {
  const tokens = JSON.parse(await readFile(tokensPath, "utf8")) as Tokens;
  const generated = generate(tokens);
  const checkOnly = process.argv.includes("--check");
  if (checkOnly) {
    let existing = "";
    try { existing = await readFile(outputPath, "utf8"); } catch { /* file does not exist yet */ }
    if (existing !== generated) {
      console.error("design/tokens.generated.css is out of date. Run `npm run tokens:generate`.");
      process.exitCode = 1;
      return;
    }
    console.log("tokens:check ok");
    return;
  }
  await writeFile(outputPath, generated);
  console.log("wrote " + outputPath);
}

await main();
