import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { chromium, type Page } from "playwright-core";
import { relayText } from "../interaction-lab/relay-forge/relay-copy.ts";
import { SUPPORTED_LOCALES } from "../i18n.ts";
import { startRelayWorkerFixture } from "../tests/browser/worker-fixture.ts";

const base = process.argv[2] || "http://127.0.0.1:5183";
assert.ok(["127.0.0.1", "localhost"].includes(new URL(base).hostname), "This fixture may only target a local server.");
const output = join(process.cwd(), ".qa-artifacts", "relay-product", "browser");
await mkdir(output, { recursive: true });
// Isolated temporary profile, without attaching to the user's browser or account.
const chromePath = process.env.QF_CHROME_PATH || (process.platform === "win32" ? "C:/Program Files/Google/Chrome/Application/chrome.exe" : "/usr/bin/google-chrome");
const browser = await chromium.launch({ executablePath: chromePath, headless: true });
const errors: string[] = [];
const results: string[] = [];
const notice = (page: Page) => page.locator(".rf-human-inbox-notice");
const widthCheck = async (page: Page) => {
  const sizes = await page.evaluate("({ width: innerWidth, scroll: document.documentElement.scrollWidth, dialog: document.querySelector('dialog')?.getBoundingClientRect().width })") as { width: number; scroll: number; dialog?: number };
  assert.ok(sizes.scroll <= sizes.width, JSON.stringify(sizes));
  assert.ok(!sizes.dialog || sizes.dialog <= sizes.width, JSON.stringify(sizes));
};
try {
  for (const width of process.argv.includes("--integration-only") ? [] : [320, 412, 1440]) for (const locale of SUPPORTED_LOCALES) {
    const context = await browser.newContext({ viewport: { width, height: 915 }, reducedMotion: "reduce" });
    const page = await context.newPage();
    page.on("pageerror", error => errors.push(error.message));
    await page.goto(`${base}/tests/browser/human-relay.html?lang=${locale}`, { waitUntil: "networkidle" });
    await page.locator("#relay-test-open").click();
    assert.equal(await page.locator(".rf-human-request summary").evaluate(element => element.matches(":focus")), true, "Opening a specific request focuses its summary");
    const approve = page.getByRole("button", { name: relayText("approve", locale), exact: true });
    assert.equal(await approve.isDisabled(), true, "Opening a request is not confirmation");
    await widthCheck(page);
    assert.equal(await page.getByRole("link", { name: relayText("external", locale) }).getAttribute("target"), "_blank");
    if ((width === 412 || width === 1440) && (locale === "ja" || locale === "en")) await page.screenshot({ path: join(output, `${locale}-${width}-pending.png`) });
    await page.getByRole("button", { name: relayText("defer", locale), exact: true }).click();
    await notice(page).filter({ hasText: relayText("deferredSaved", locale) }).waitFor();
    await page.locator('[data-status="deferred"]').click();
    if (await page.locator("details").getAttribute("open") === null) await page.locator("summary").click();
    await page.getByRole("button", { name: relayText("resume", locale), exact: true }).click();
    await notice(page).filter({ hasText: relayText("resumed", locale) }).waitFor();
    await page.locator('[data-status="pending"]').click();
    if (!await page.locator("details").getAttribute("open").then(value => value !== null)) await page.locator("summary").click();
    await page.getByRole("textbox").fill("The close button needs more space.");
    await page.getByRole("checkbox", { name: relayText("checked", locale), exact: true }).check();
    await page.getByRole("button", { name: relayText("revise", locale), exact: true }).click();
    await notice(page).filter({ hasText: relayText("saved", locale) }).waitFor();
    assert.equal(await notice(page).evaluate(element => element.getAnimations().length), 0, "Reduced motion disables feedback animation");
    await page.locator('[data-status="answered"]').click();
    assert.match(await page.locator(".rf-human-inbox-list").textContent() || "", /The close button needs more space/);
    const saved = JSON.parse(await page.locator("#relay-test-status").textContent() || "{}");
    assert.equal(saved.originalDone, false);
    assert.equal(saved.requests[0].done, true);
    await page.keyboard.press("Escape");
    assert.equal(await page.evaluate("document.activeElement?.id"), "relay-test-open");
    results.push(`${locale} ${width}: defer/resume/feedback, explicit check, focus, no original completion, reduced motion`);
    await context.close();
  }
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  page.on("pageerror", error => errors.push(error.message));
  await page.goto(`${base}/tests/browser/human-relay.html?lang=ja`);
  await page.locator("#relay-test-network").click();
  await page.locator("#relay-test-open").click();
  await page.getByRole("textbox").fill("Keep this draft after failure.");
  await page.getByRole("checkbox", { name: relayText("checked", "ja"), exact: true }).check();
  await page.getByRole("button", { name: relayText("revise", "ja"), exact: true }).click();
  await notice(page).filter({ hasText: relayText("failed", "ja") }).waitFor();
  assert.equal(await page.getByRole("textbox").inputValue(), "Keep this draft after failure.");
  await page.keyboard.press("Escape");
  await page.locator("#relay-test-stale").click();
  await page.locator("#relay-test-open").click();
  await page.getByRole("button", { name: relayText("revise", "ja"), exact: true }).click();
  await notice(page).filter({ hasText: relayText("stale", "ja") }).waitFor();
  assert.equal(await page.getByRole("checkbox", { name: relayText("checked", "ja"), exact: true }).isChecked(), false);
  assert.equal(await page.getByRole("textbox").inputValue(), "Keep this draft after failure.");
  await page.keyboard.press("Escape");
  await page.getByRole("checkbox", { name: relayText("motion", "ja"), exact: true }).uncheck();
  await page.locator("#relay-test-open").click();
  await page.getByRole("checkbox", { name: relayText("checked", "ja"), exact: true }).check();
  await page.getByRole("button", { name: relayText("approve", "ja"), exact: true }).click();
  await notice(page).filter({ hasText: relayText("saved", "ja") }).waitFor();
  assert.equal(await notice(page).evaluate(element => element.getAnimations().length), 0);
  results.push("Network/stale errors preserve drafts; stale invalidates check; motion preference disables animation; no-change answer saves");
  await page.goto(`${base}/interaction-lab/relay-forge/?fixture=base`);
  // At medium desktop widths the existing Lens is a modal; dismiss it normally.
  await page.keyboard.press("Escape");
  await page.locator(".rf-human-inbox-trigger:visible").first().click();
  await page.locator(".rf-human-inbox[open]").waitFor();
  results.push("Integrated Relay Forge shell opens Human inbox without runtime errors");
  const fixture = await startRelayWorkerFixture(new URL(base).origin);
  try {
    await page.goto(`${base}/tests/browser/production-relay.html?api=${encodeURIComponent(fixture.baseUrl)}&uid=${fixture.uid}`);
    await page.locator(".rf-human-inbox-trigger:visible").first().waitFor();
    await page.keyboard.press("Escape");
    await page.locator(".rf-human-inbox-trigger:visible").first().click();
    await page.locator(".rf-human-inbox summary").click();
    await page.getByRole("textbox").fill("Please make the button larger.");
    await page.getByRole("checkbox", { name: relayText("checked", "ja"), exact: true }).check();
    await page.getByRole("button", { name: relayText("revise", "ja"), exact: true }).click();
    await notice(page).filter({ hasText: relayText("saved", "ja") }).waitFor();
    const answered = await fixture.mcp("list_human_requests", { status: "answered" });
    assert.equal(answered.quests[0].humanRequest?.response, "Please make the button larger.");
    assert.equal((await fixture.web(`/v1/quests/${fixture.first.source.id}`)).quest.done, false);
    await page.reload();
    await page.locator(".rf-human-inbox-trigger:visible").first().waitFor();
    await page.keyboard.press("Escape");
    await page.locator(".rf-human-inbox-trigger:visible").first().click();
    await page.locator('[data-status="answered"]').click();
    await page.locator(".rf-human-inbox summary").click();
    assert.match(await page.locator(".rf-human-inbox-list").textContent() || "", /Please make the button larger/);
    await page.screenshot({ path: join(output, "integrated-worker-answer.png") });
    await page.getByRole("button", { name: relayText("source", "ja"), exact: true }).click();
    await page.locator(".rf-quest-context").filter({ hasText: "Review Human" }).waitFor();
    const second = await fixture.receive("second");
    await page.keyboard.press("Escape");
    await page.locator(".rf-human-inbox-trigger:visible").first().click();
    await page.locator('[data-status="pending"]').click();
    await page.locator(`[data-request-id="${second.quest.id}"] summary`).click();
    await page.getByRole("textbox").fill("Keep focus while another request arrives.");
    await fixture.receive("third");
    await page.evaluate("window.dispatchEvent(new Event('focus'))");
    await notice(page).filter({ hasText: "新着: 1" }).waitFor();
    assert.equal(await page.evaluate("document.activeElement?.tagName"), "TEXTAREA");
    assert.equal(await page.getByRole("textbox").inputValue(), "Keep focus while another request arrives.");
    const focusedAction = page.getByRole("button", { name: relayText("defer", "ja"), exact: true });
    await focusedAction.focus();
    await fixture.receive("fourth");
    await fixture.receive("fifth");
    await page.evaluate("window.dispatchEvent(new Event('focus'))");
    await notice(page).filter({ hasText: "新着: 2" }).waitFor();
    assert.equal(await focusedAction.evaluate(element => element.matches(":focus")), true, "Background refresh preserves keyboard action focus");
    await page.keyboard.press("Escape");
    await page.getByRole("button", { name: "Settings", exact: true }).first().click();
    const onboarding = page.locator(".rf-relay-onboarding");
    assert.ok((await onboarding.textContent() || "").includes(relayText("registerAgent", "ja")));
    const connection = page.locator('.rf-set-connection-card[data-linked="true"]');
    assert.match(await connection.textContent() || "", /My Review Agent/);
    assert.match(await connection.textContent() || "", /quests:write/);
    assert.doesNotMatch(await connection.textContent() || "", /agents:write/);
    await onboarding.screenshot({ path: join(output, "integrated-onboarding.png") });
    await page.getByRole("button", { name: "Skills", exact: true }).first().click();
    await page.getByRole("searchbox", { name: "Skillsを検索" }).fill("request_human_review");
    await page.locator(".rf-skills-tool-name").filter({ hasText: "request_human_review" }).waitFor();
    results.push("MCP arrival preserves input and action focus; source navigation shows real requester; onboarding intersects permissions; Skills finds the new tool");
    await page.setViewportSize({ width: 412, height: 915 });
    await page.reload();
    await page.locator(".rf-m-holder-name").filter({ hasText: "My Review Agent" }).waitFor();
    await page.locator(".rf-human-inbox-trigger:visible").first().click();
    await page.locator(`[data-request-id="${second.quest.id}"] summary`).click();
    await widthCheck(page);
    await page.getByRole("checkbox", { name: relayText("checked", "ja"), exact: true }).check();
    let releaseRead!: () => void;
    let readStarted!: () => void;
    const readGate = new Promise<void>(resolve => { releaseRead = resolve; });
    const readReady = new Promise<void>(resolve => { readStarted = resolve; });
    await page.route(`${fixture.baseUrl}/v1/human-requests?*`, async route => {
      const response = await route.fetch();
      readStarted();
      await readGate;
      await route.fulfill({ response });
    });
    try {
      await page.getByRole("button", { name: relayText("refresh", "ja"), exact: true }).click();
      await readReady;
      await page.getByRole("button", { name: relayText("approve", "ja"), exact: true }).click();
      await notice(page).filter({ hasText: relayText("saved", "ja") }).waitFor();
    } finally { releaseRead(); }
    await page.waitForFunction("!document.querySelector('.rf-human-inbox > div button').disabled");
    assert.equal(await page.locator(`[data-request-id="${second.quest.id}"]`).count(), 0, "A delayed pre-answer list cannot return answered work to the pending inbox");
    await page.unroute(`${fixture.baseUrl}/v1/human-requests?*`);
    results.push("A delayed inbox read cannot overwrite a saved Human answer or its pending count");
    await page.screenshot({ path: join(output, "integrated-mobile.png") });
    assert.equal((await fixture.mcp("list_human_requests", { status: "answered" })).quests.length, 2);
    results.push("412px production UI saves a no-change response through HTTP and MCP reads it back");
    results.push("HTTP Worker + production UI + MCP: Agent request, Human feedback, Agent readback, reload, independent original completion");

    const abandoned = await fixture.receive("abandoned-preview");
    await page.reload();
    await page.locator(".rf-human-inbox-trigger:visible").first().click();
    await page.locator(`[data-request-id="${abandoned.quest.id}"] summary`).click();
    await page.getByRole("checkbox", { name:relayText("checked", "ja"), exact:true }).check();
    let releasePreview!: () => void;
    let previewStarted!: () => void;
    const previewGate = new Promise<void>(resolve => { releasePreview = resolve; });
    const previewReady = new Promise<void>(resolve => { previewStarted = resolve; });
    let executed = 0;
    await page.route(`${fixture.baseUrl}/v1/quests/${abandoned.quest.id}/review-response`, async route => {
      if (route.request().postDataJSON().dryRun === false) executed++;
      const response = await route.fetch();
      previewStarted();
      await previewGate;
      await route.fulfill({ response });
    });
    try {
      await page.getByRole("button", { name:relayText("approve", "ja"), exact:true }).click();
      await previewReady;
      await page.evaluate("window.dispatchEvent(new Event('test:unmount'))");
    } finally { releasePreview(); }
    await page.waitForLoadState("networkidle");
    assert.equal(executed, 0, "Disposing the workspace during dry-run must not start a real answer");
    assert.equal((await fixture.web(`/v1/quests/${abandoned.quest.id}`)).quest.humanRequest?.status, "pending");
    results.push("Disposing the workspace during Human-response preview never starts an answer write");
  } finally { await fixture.close(); }
  assert.deepEqual(errors, []);
  await writeFile(join(output, "results.json"), JSON.stringify({ results, errors, note: "Local browser/domain fixture. Does not certify physical Pixel 9 or live Codex/OpenClaw clients." }, null, 2));
  console.log(`PASS ${results.length} browser scenarios; no page errors`);
} finally { await browser.close(); }
